vo=gpu
gpu-api=opengl
# gpu-context=wayland

hwdec=vaapi
hwdec-codecs=all
vd-lavc-dr=yes
vd-lavc-threads=4

vd-lavc-fast=yes

scale=lanczos
dscale=mitchell
dither-depth=auto

demuxer-max-bytes=64MiB
demuxer-max-back-bytes=20MiB
cache=no

target-colorspace-hint=yes
target-peak=auto

volume=50
audio-device=auto

osc=no
osd-bar=no

screenshot-format=png
screenshot-directory=~/Documents
screenshot-template="mpv-%F-%P-%#n"

term-osd-bar=yes
term-osd-bar-chars="[=>-]"
